using PersianHub.API.Enums.Layer1Hook;

namespace PersianHub.API.DTOs.Layer1Hook;

public record CreateEventDto(
    string Title,
    string? TitleFa,
    string? Slug,
    string? Description,
    string? DescriptionFa,
    string? LocationName,
    string? LocationNameFa,
    string? AddressLine,
    string? AddressLineFa,
    string? City,
    string? CityFa,
    string? Region,
    string? RegionFa,
    string? PostalCode,
    string? Country,
    DateTime StartsAtUtc,
    DateTime? EndsAtUtc,
    int? BusinessId,
    string? OrganizerName,
    string? OrganizerNameFa,
    string? OrganizerPhoneNumber,
    string? OrganizerEmail,
    string? CoverImageUrl,
    bool IsFree,
    decimal? Price,
    string? Currency,
    int? CreatedByUserId
);

public record UpdateEventDto(
    string Title,
    string? TitleFa,
    string? Description,
    string? DescriptionFa,
    string? LocationName,
    string? LocationNameFa,
    string? AddressLine,
    string? AddressLineFa,
    string? City,
    string? CityFa,
    string? Region,
    string? RegionFa,
    string? PostalCode,
    string? Country,
    DateTime StartsAtUtc,
    DateTime? EndsAtUtc,
    int? BusinessId,
    string? OrganizerName,
    string? OrganizerNameFa,
    string? OrganizerPhoneNumber,
    string? OrganizerEmail,
    string? CoverImageUrl,
    bool IsFree,
    decimal? Price,
    string? Currency
);

public record EventDto(
    int Id,
    string Title,
    string? TitleFa,
    string Slug,
    string? Description,
    string? DescriptionFa,
    string? LocationName,
    string? LocationNameFa,
    string? AddressLine,
    string? AddressLineFa,
    string? City,
    string? CityFa,
    string? Region,
    string? RegionFa,
    string? PostalCode,
    string? Country,
    DateTime StartsAtUtc,
    DateTime? EndsAtUtc,
    int? BusinessId,
    string? OrganizerName,
    string? OrganizerNameFa,
    string? OrganizerPhoneNumber,
    string? OrganizerEmail,
    string? CoverImageUrl,
    bool IsFree,
    decimal? Price,
    string? Currency,
    EventStatus Status,
    bool IsPublished,
    int? CreatedByUserId,
    DateTime CreatedAtUtc,
    DateTime UpdatedAtUtc
);

public record EventListItemDto(
    int Id,
    string Title,
    string? TitleFa,
    string Slug,
    string? City,
    string? CityFa,
    DateTime StartsAtUtc,
    bool IsFree,
    decimal? Price,
    string? Currency,
    EventStatus Status,
    bool IsPublished,
    string? CoverImageUrl,
    int? BusinessId
);
