using PersianHub.API.Enums.Layer1Hook;

namespace PersianHub.API.DTOs.Admin;

public record AdminEventListItemDto(
    int Id,
    string Title,
    string? TitleFa,
    string Slug,
    string? City,
    string? CityFa,
    DateTime StartsAtUtc,
    DateTime? EndsAtUtc,
    int? BusinessId,
    string? BusinessName,
    bool IsFree,
    decimal? Price,
    string? Currency,
    EventStatus Status,
    bool IsPublished,
    string? CoverImageUrl,
    DateTime CreatedAtUtc
);

public record AdminEventDetailDto(
    int Id,
    string Title,
    string? TitleFa,
    string Slug,
    string? Description,
    string? DescriptionFa,
    string? LocationName,
    string? LocationNameFa,
    string? AddressLine,
    string? AddressLineFa,
    string? City,
    string? CityFa,
    string? Region,
    string? RegionFa,
    string? PostalCode,
    string? Country,
    DateTime StartsAtUtc,
    DateTime? EndsAtUtc,
    int? BusinessId,
    string? BusinessName,
    string? OrganizerName,
    string? OrganizerNameFa,
    string? OrganizerPhoneNumber,
    string? OrganizerEmail,
    string? CoverImageUrl,
    bool IsFree,
    decimal? Price,
    string? Currency,
    EventStatus Status,
    bool IsPublished,
    int? CreatedByUserId,
    DateTime CreatedAtUtc,
    DateTime UpdatedAtUtc
);

public record AdminCreateEventDto(
    string Title,
    string? TitleFa,
    string? Slug,
    string? Description,
    string? DescriptionFa,
    string? LocationName,
    string? LocationNameFa,
    string? AddressLine,
    string? AddressLineFa,
    string? City,
    string? CityFa,
    string? Region,
    string? RegionFa,
    string? PostalCode,
    string? Country,
    DateTime StartsAtUtc,
    DateTime? EndsAtUtc,
    int? BusinessId,
    string? OrganizerName,
    string? OrganizerNameFa,
    string? OrganizerPhoneNumber,
    string? OrganizerEmail,
    string? CoverImageUrl,
    bool IsFree,
    decimal? Price,
    string? Currency,
    int? CreatedByUserId
);

public record AdminUpdateEventDto(
    string Title,
    string? TitleFa,
    string? Description,
    string? DescriptionFa,
    string? LocationName,
    string? LocationNameFa,
    string? AddressLine,
    string? AddressLineFa,
    string? City,
    string? CityFa,
    string? Region,
    string? RegionFa,
    string? PostalCode,
    string? Country,
    DateTime StartsAtUtc,
    DateTime? EndsAtUtc,
    int? BusinessId,
    string? OrganizerName,
    string? OrganizerNameFa,
    string? OrganizerPhoneNumber,
    string? OrganizerEmail,
    string? CoverImageUrl,
    bool IsFree,
    decimal? Price,
    string? Currency
);
