using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PersianHub.API.Common;
using PersianHub.API.DTOs.Admin;
using PersianHub.API.Enums.Layer3Network;
using PersianHub.API.Interfaces.Admin;

namespace PersianHub.API.Controllers.Admin;

/// <summary>
/// Admin moderation of invite rewards.
/// Admin can approve, reject, or mark rewards as granted.
/// No create/delete — rewards are system-generated by the referral/invite flow.
/// </summary>
[Route("api/v1/admin/invite-rewards")]
[Authorize(Roles = AppRoles.Admin)]
public sealed class AdminInviteRewardsController(IAdminInviteRewardService rewardService) : ApiControllerBase
{
    /// <summary>Paginated list of all invite rewards with optional filters.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(object), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetAll(
        [FromQuery] int? userId,
        [FromQuery] RewardStatus? status,
        [FromQuery] RewardType? rewardType,
        [FromQuery] int? referralId,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20,
        CancellationToken ct = default)
    {
        var result = await rewardService.GetAllAsync(userId, status, rewardType, referralId, page, pageSize, ct);
        return Ok(result);
    }

    /// <summary>Returns full details for an invite reward by id.</summary>
    [HttpGet("{id:int}")]
    [ProducesResponseType(typeof(AdminInviteRewardDetailDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetById(int id, CancellationToken ct)
        => MapResult(await rewardService.GetByIdAsync(id, ct));

    /// <summary>Approves a pending reward — sets status to Granted and records GrantedAtUtc.</summary>
    [HttpPatch("{id:int}/approve")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Approve(int id, CancellationToken ct)
        => MapResult(await rewardService.ApproveAsync(id, ct));

    /// <summary>Rejects a pending reward — sets status to Expired.</summary>
    [HttpPatch("{id:int}/reject")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Reject(int id, CancellationToken ct)
        => MapResult(await rewardService.RejectAsync(id, ct));

    /// <summary>Marks a reward as granted — use when reward has been manually fulfilled.</summary>
    [HttpPatch("{id:int}/mark-granted")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> MarkGranted(int id, CancellationToken ct)
        => MapResult(await rewardService.MarkGrantedAsync(id, ct));
}
